[DRFT-885] Remove unused NodeJS package from base image
RedHatInsights/drift-backend pull request #302
Opened 2021-10-21 15:35 UTC by johnsonm325

This PR removes NPM and its is dependencies including NodeJS, which are not used by drift-backend but their presence in the base image provides potential pathway for security vulnerabilities.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-11-01 13:55 UTC, petrblaho commented on Dockerfile
> +    yum remove -y npm \
There are missing `&&` as on lines above and below.

2021-11-01 13:56 UTC, petrblaho commented on Dockerfile
> +    yum upgrade -y --security \
Ditto for missing `&&`.

2021-11-01 13:57 UTC, petrblaho requested changes
Build process fails as it tries to run one big mangled command.
Add `&&` as noted and it should work.

2021-11-03 12:36 UTC, petrblaho approved these changes
LGTM!

2021-11-03 12:45 UTC, merged

2021-11-03 15:01 UTC, sthirugn commented
> Build process fails as it tries to run one big mangled command. Add `&&` as noted and it should work.

Great catch, Petr thanks